---
title: "Final Project"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---


```{r, include = FALSE}
library(tidyverse)
library(plotly)
library(lubridate)
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(ggridges)
library(usdata)
library(usmap)
library(ggplot2)
library(patchwork)
library(plotly)
library(leaflet)
```

```{r, message = FALSE, warning = FALSE}

daily_cases = read_csv("./data/case_daily_trends__united_states.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    date = mdy(case_daily_trends_united_states),
    new_cases = as.double(x2),
    seven_day_ma = as.double(x3)) %>% 
  select(date, new_cases, seven_day_ma) %>% 
  slice(-1:-3) %>% 
  map_df(rev) 



```

## Daily Trends in Number of COVID-19 Cases in the United States Reported

```{r, message = FALSE, warning = FALSE}
line.fmt = list(dash="solid", width = 1.5, color= "viridius")
 
daily_cases %>% 
  plot_ly(x = ~date, y = ~new_cases, type = "bar", name = "Daily New Cases") %>% 
  add_lines( x=~date, y = ~seven_day_ma, line=line.fmt, name = "7-Day Moving Average") %>% 
  layout(xaxis = list(title = "Date"), yaxis = list(title = "Daily New Cases"))
```

## Daily Trends in Number of COVID-19 Deaths in the United States 
```{r, message = FALSE, warning = FALSE}
daily_deaths = read_csv("./data/death_daily_trends__united_states.csv") %>%
  janitor::clean_names() %>% 
  mutate(
    date = mdy(death_daily_trends_united_states),
    new_deaths = as.double(x2),
    seven_day_ma = as.double(x3)) %>% 
    select(date, new_deaths, seven_day_ma) %>% 
    slice(-1:-3) %>% 
    map_df(rev)
```

```{r, message = FALSE, warning = FALSE}
line.fmt = list(dash="solid", width = 1.5, color= "viridius")
 
daily_deaths %>% 
  plot_ly(x = ~date, y = ~new_deaths, type = "bar", name = "Daily New Deaths") %>% 
  add_lines( x=~date, y = ~seven_day_ma, line=line.fmt, name = "7-Day Moving Average") %>% 
  layout(xaxis = list(title = "Date"), yaxis = list(title = "Daily New Deaths"))
```



#### introducing first dataset "covid_impact_on_airport_traffic"
```{r}
#import data for covid_impact_on_airport_traffic
#Main Problem: join data, have date and state match for both data
# Transportation and Covid have different way to representing date(2020-01-01 in transportation date and 01/01/2020 in Covid data)
transportation = 
   read_csv("./data/covid_impact_on_airport_traffic.csv" ) %>%
  janitor::clean_names() %>%
  filter(country != "Australia" & country != "Chile" & country != "Canada") %>% #only leave United States data 
   separate(date, c("year","month","day"), sep = "([-])") %>%  # I re-arrange the date information so that it matched the date format in Covid data
    mutate(date = paste(month,day,year,sep = "/")) %>% # I re-arrange the date information so that it matched the date format in Covid data
  relocate(date) %>% 
  select(-year,-month,-day,-version,-aggregation_method,-state,-country) %>% #delete variable that is not in our interest
    rename(state = iso_3166_2) %>% #rename state variable so that we can combine two data 
  mutate(state=gsub("US-","",state)) # reformat state variable, delete prefix of US-
```

#### introducing first dataset "United_States_Covid-19_Cases_and_Deaths_by_State_over_Time"
```{r, message = FALSE, warning = FALSE}
Covid =  
  read_csv("./data/United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv" ) %>%
  janitor::clean_names() %>%
  filter(consent_cases == "Agree" | consent_deaths == "Agree")%>% #need to decided whether this step is necessary
  select("submission_date":"pnew_death") %>% #select variable of interest, need to look further into which variable we are interested in and way
    rename(date = submission_date)  # rename date variable so that we can match data accordingly
  
```

#### Joining two dataset
```{r, message = FALSE, warning = FALSE}
Covid_transport_data = 
  left_join(transportation, Covid, by = c("date")) %>% #left join two data, by date
  filter(state.y == state.x) 
  #filter the data so that we only leave the data that have matching date and state
```

### Bubble Map

```{r}
transport_state = 
  Covid_transport_data %>% 
  mutate(centroid=gsub("POINT\\D","",centroid)) %>% 
  separate(centroid, into = c("long", "lat"), sep = 17) %>% 
  mutate(across(where(is.character), str_trim)) %>% 
  group_by (airport_name, long, lat, state.x) %>% 
  summarize(
    mean_percent_base = mean(percent_of_baseline)
    ) %>% 
  mutate(long = round(as.double(long),digits = 0),
         lat = round(as.double(str_remove(lat,"\\)"))),digits = 2,
         mean_percent_base = round(mean_percent_base, digits = 2))


```


```{r}

mybins <- seq(40, 90, by=10)
mypalette <- colorBin( palette="magma", domain=transport_state$mean_percent_base,  bins=mybins)

```

```{r}
mytext = paste(
   "Longitude: ", transport_state$long, 
   "Latitude: ", transport_state$lat, 
   "Percent of baseline: ", transport_state$mean_percent_base) %>%
  lapply(htmltools::HTML)
```

```{r}
m <- leaflet(transport_state) %>% 
  addTiles()  %>% 
  addProviderTiles("CartoDB.Positron") %>%
  addCircleMarkers(~long, ~lat, 
    fillColor = ~mypalette(mean_percent_base),
    fillOpacity = 0.7, 
    color="white", 
    radius = ~ mean_percent_base/2,
    stroke = FALSE, 
    label = mytext,
    labelOptions = labelOptions( style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto")
  ) %>%
  addLegend( pal= mypalette, values=~mean_percent_base, opacity=1, title = "Percent of baseline", position = "bottomright" )
  
m

```








